### PR TITLE
Add pry-rails and pry-byebug gems

### LINKED ISSUE #108: Add pry-rails to the Gemfile
Please add `pry-rails` and `pry-byebug`, thanks!

### PR DESCRIPTION
**Pull request by RafaelPrallon**
Resolves #108

### CODE REVIEW

**Comment by sanchez2210** [comment]
Why is this failing?

**Comment by Exellin** [comment]
You can click and see the details in the travis CI build.  Right now it shows the arrays don't match because in of the specs the arrays are being compared with .ew instead of .match_array.  You can either make a new PR to pull this fix in, or wait until my PR gets pulled in which has the fix included.

**Comment by sanchez2210** [comment]
I see, strange. Why wasn't this failing before then? Since this PR certainly didn't introduce the error. Did this just randomly pass before?

**Comment by Exellin** [comment]
Yeah sometimes the array is equal and sometimes the order gets changed.  Not sure what triggers the change.

**Comment by vamsipavanmahesh** [comment]
Do you think adding   `has_many :inventory_users, -> { order(user_id: :asc) }` in inventory.rb will fix this? @pachonk

**Comment by pachonk** [comment]
@RafaelPrallon That test was fixed, but I can't merge until Travis is passing. Please rebase (https://github.com/emerald-rubies/guides/blob/master/git/keep-feature-branches-up-to-date.md) and after Travis passes I can merge.

**Pull request merged**
