### PR TITLE
Remove unneeded faker require in inventory factory

### PR DESCRIPTION
**Pull request by Exellin**

### CODE REVIEW

**Comment by pachonk** [comment]
@Exellin rebase and fix merge conflict plz

**Comment by Exellin** [comment]
When I rebase I'm not getting any merge conflicts.

**Comment by pachonk** [comment]
Did you fetch before rebase?

**Comment by Exellin** [comment]
Yeah I did the following

git fetch upstream
git checkout upstream/master
git checkout make-inventory-model-plural
git rebase master --preserve-merges (looked for a way to rebase where I'm not changing any commits, however I also tried git rebase -i upstream/master and instead of the commit there is a line saying noop)
git push -f

**Pull request merged**
